# Default plugin configs - Avoid touching unless you have to

postCssPlugins:
    -
        name: 'autoprefixer'
        options:
            #browsers: ['last 2 version', 'IE 7']
            #cascade: true
    -
        name: 'cssnano'
        options:
            zindex: false

uglify:
    mangle: false
    compress: true

revEasy:
    revType: 'date'
